POST {{user-api}}/users/sign-up
Content-Type: application/json

{
  "provider": "GOOGLE",
  "providerAccessToken": "ya29.a0Ae4lvC3UyMqaDvXFBJdlBE0JVO9t246L2nUfEdTFaicC-lERH22h2JSxaU2Mmip8N8VWis7fZmfHIQshmj-E8a1CqvkqxItzz2CdXmripeu4RKqHweyzvu1-lbTkfYeBoNDFZ1HRQcieA0jXDgETiW4c1euh9ti2XEpJwg"
}

###
POST {{user-api}}/users/sign-in
Content-Type: application/json

{
  "provider": "GOOGLE",
  "providerAccessToken": "ya29.a0Ae4lvC3UyMqaDvXFBJdlBE0JVO9t246L2nUfEdTFaicC-lERH22h2JSxaU2Mmip8N8VWis7fZmfHIQshmj-E8a1CqvkqxItzz2CdXmripeu4RKqHweyzvu1-lbTkfYeBoNDFZ1HRQcieA0jXDgETiW4c1euh9ti2XEpJwg"
}

###
POST {{user-api}}/users/sign-out
Content-Type: application/json

{
  "refresh_token": "baedc3bd-6a6f-4a63-b0b8-b590260b4985"
}

###
POST {{user-api}}/users/token-refresh
Content-Type: application/json

{
  "refresh_token": "3865871b-6f49-4cbd-8520-0c3e4eff283b"
}

###

