POST http://{{monolith}}/notices
Content-Type: application/json
Authorization: Bearer {{access-token}}

{
  "title": "title",
  "content": "content"
}

###

GET http://{{monolith}}/notices/7

###

PUT http://{{monolith}}/notices/7
Content-Type: application/json
Authorization: Bearer {{access-token}}

{
  "title": "new title",
  "content": "new content"
}

###

DELETE http://{{monolith}}/notices/7
Content-Type: application/json
Authorization: Bearer {{access-token}}

