POST {{auth-api}}/users/sign-up
Content-Type: application/json

{
  "provider": "GOOGLE",
  "providerAccessToken": "ya29.a0AfH6SMBl5JBev4-NEIZYL0OFIIfGLHJ_dC3BreMVCQRWZipJUx8rzIdIqsYFScZu0t32RcDPyU3Vz06altwHaRNeMkYX2urVuD88tBKguDOon8edhvJVwfjpF9XWv0odU5WN3z1OiHDu4VJuFsiCthOJyG8STlq_5soO",
  "nickname": "nickname1"
}

###
POST {{auth-api}}/users/sign-in
Content-Type: application/json

{
  "provider": "GOOGLE",
  "providerAccessToken": "ya29.a0AfH6SMCtNWFlIT_yVGQaNq20PzdobS98dqhHBLT3YMRpsupW5ockIKk6gQsVWZPaAyB9IYvQymGbnru_TX0CPZx-86brok8BKvNGdKzyB0t-iNx_hN7lu005py41C6fCFdngJOMzGzHEmgzhgkS3hAI-_Qrh4AKJopA"
}

###
POST {{auth-api}}/users/sign-out
Content-Type: application/json

{
  "refresh_token": "baedc3bd-6a6f-4a63-b0b8-b590260b4985"
}

###
POST {{auth-api}}/users/token-refresh
Content-Type: application/json

{
  "refresh_token": "3f103e78-ddda-4d75-9040-3e0ae6aa440c"
}

###
POST {{auth-api}}/oauth/check_token
Authorization: Basic Zmlyc3QtY2xpZW50Om5vb25ld2lsbGV2ZXJndWVzcw== # first-client:noonewilleverguess
Content-Type: application/x-www-form-urlencoded

token=7ed8b4f4-87a1-4e6d-896a-b70b516db8ac

###


