spring:
  main:
    banner-mode: 'off'
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: false
  data:
    web:
      pageable:
        one-indexed-parameters: true
  jackson:
    mapper:
      default-view-inclusion: true
      accept-case-insensitive-enums: true
  flyway:
    enabled: false

cloud:
  aws:
    s3:
      bucket: kiworkshop
    region:
      static: ap-northeast-2
    stack:
      auto: false

security:
  oauth2:
    client:
      client-id: first-client
      client-secret: noonewilleverguess
    resource:
      token-info-uri: http://localhost:8081/oauth/check_token
