server:
  port: 8081
spring:
  main:
    banner-mode: 'off'
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
  data:
    web:
      pageable:
        one-indexed-parameters: true
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true
