spring:
  main:
    banner-mode: 'off'
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: false
    hibernate:
      ddl-auto: none
  data:
    web:
      pageable:
        one-indexed-parameters: true
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true

