CREATE TABLE notice (
    id BIGINT NOT NULL AUTO_INCREMENT,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '생성일자',
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '수정일자',
    title VARCHAR(255) NOT NULL DEFAULT '' COMMENT '제목',
    content TEXT NOT NULL DEFAULT '' COMMENT '내용',
    PRIMARY KEY (id)
);