server:
  port: 8081
spring:
  profiles:
    active: "local"
  main:
    banner-mode: 'off'
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
  data:
    web:
      pageable:
        one-indexed-parameters: true
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true
  flyway:
    enabled: false

security:
  oauth2:
    client:
      client-id: first-client
      client-secret: noonewilleverguess
service:
  auth-api: http://localhost:8082

---

spring:
  profiles: local-db
  datasource:
    schema: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 60000
      connection-timeout: 3000
    platform: mysql
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
