POST {{auth}}/users/sign-up
Content-Type: application/json

{
  "provider": "GOOGLE",
  "providerAccessToken": "ya29.a0AfH6SMB1RqYmN1KpH0BbhjM_10lpyioOqjhxBn0-fWUItW9wf0j2as9cWgTf2bAXgcgRmEae4tIp68mkigZ2-KEQQYy85VCwcAkviZ_mxUNxLZqZW1gqtQ8umEh_S82BZveoh1d-gh_k4SuVA8NYEm7YSdoyCWLA-Fe4",
  "nickname": "김명재"
}

###
POST {{auth}}/users/sign-in
Content-Type: application/json

{
  "provider": "GOOGLE",
  "providerAccessToken": "ya29.a0AfH6SMBSeqq1AdEDAi2yGgIO37wiP-s0dN2VMiZOSt5a5-9XMUDBjrXyA9ttORCnkUxbAHzEeMskFesR0XEoCO8ZDTxAN_KcuEVDEpGAGKyVj4YGsuX2rHay7ENYrxgbqH8G48QGrQCSfp_Bfr4CM6OQ9-vVKFWRtgR7"
}

###
POST {{auth}}/users/sign-out
Content-Type: application/json

{
  "refresh_token": "baedc3bd-6a6f-4a63-b0b8-b590260b4985"
}

###
POST {{auth}}/users/token-refresh
Content-Type: application/json

{
  "refresh_token": "3f103e78-ddda-4d75-9040-3e0ae6aa440c"
}

###
POST {{auth}}/oauth/check_token
Authorization: Basic Zmlyc3QtY2xpZW50Om5vb25ld2lsbGV2ZXJndWVzcw== # first-client:noonewilleverguess
Content-Type: application/x-www-form-urlencoded

token=5cd89de9-926d-4752-8559-bb23515c1bd7

###


