server:
  port: 8081
spring:
  profiles:
    active: "local"
  main:
    banner-mode: 'off'
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
        format_sql: true
  data:
    web:
      pageable:
        one-indexed-parameters: true
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true
  flyway:
    enabled: false
    locations: 'filesystem:../../db-migration'

security:
  oauth2:
    client:
      client-id: first-client
      client-secret: noonewilleverguess
service:
  auth-api: http://localhost:8081

---

spring:
  profiles: local-db
  datasource:
    schema: ""
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      max-lifetime: 60000
      connection-timeout: 3000
    url: "jdbc:mysql://0.0.0.0:3307/community"
    username: mariadb
    password: secret
  jpa:
    hibernate:
      ddl-auto: none

---

spring:
  profiles: local-docker
  datasource:
    schema: ""
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      max-lifetime: 60000
      connection-timeout: 3000
    url: 'jdbc:mysql://host.docker.internal:3307/community'
    username: mariadb
    password: secret
  jpa:
    hibernate:
      ddl-auto: none

---

spring:
  profiles: prod
  datasource:
    schema: ""
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      max-lifetime: 60000
      connection-timeout: 3000
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false

security:
  oauth2:
    client:
      client-id: ${OAUTH_CLIENT_ID}
      client-secret: ${OAUTH_CLIENT_SECRET}
